### ISSUE TITLE
Filter is not passed to db.get

### ISSUE THREAD

**Issue by sean-roberts** [micro-analytics/micro-analytics-cli#33]
We are not passing filter options to db.get()

**Comment by sean-roberts** [comment]
I'll fix after the wildcard stuff is merged...

**Comment by mxstbr** [comment]
Need to add tests for that too, to make sure we don't regress.

**Comment by sean-roberts** [comment]
we also don't support passing options under the field of 'filter'

**Comment by 7rulnik** [comment]
@relekang I can take this issue.
Should we increment currentViews and push view if `since` or `before` query passed?

**Comment by relekang** [comment]
Great 🙂

> Should we increment currentViews and push view if since or before query passed?

Not sure, but as a start we should just pass the filters to `get` all the places.
