### ISSUE TITLE
fair-analytics

### ISSUE THREAD

**Issue by vesparny** [micro-analytics/micro-analytics-cli#57]
Hi,

inspired but some of your work on micro-analytics I released [fair-analytics](https://github.com/vesparny/fair-analytics).

The approach is quite different in its implementation.
* It uses an [append-only](https://github.com/mafintosh) algorithm to store raw visit logs. This makes collected data accessible to users.
* instead of GET it uses POST to write data to the log file
* it is possible to listen to append events from other processes (for aggregating data in a *real* database and display fancy charts for instance)

<del>I will definitely mention micro-analytics in my project because you, with your work, played a big part 💯</del> 

I mentioned micro-analytics in the readme of my project, thanks for being such an inspiration.

I'd love to have your feedback, and hope you will find the project useful.

cheers.

**Comment by relekang** [comment]
Interesting, I have been wanting to write a p2p adapter were each node can use any adapter as local storage engine, but with the in-memory as default. Might look into this for inspiration :v:

**Comment by mxstbr** [comment]
Yeah it looks great, good work @vesparny!

We should totally write a p2p adapter @relekang
